### ISSUE TITLE
[Help] How to train a model using this Dataset?

### ISSUE THREAD

**Issue by Drjacky** [softwaresec-labs/LVDAndro#1]
Any link or help on how to train a model using your combined dataset 3?

**Comment by softwaresec-labs** [comment]
Hi, please refer to our another work on https://doi.org/10.1007/978-3-031-37586-6_20 or https://github.com/softwaresec-labs/ACVED

**Comment by softwaresec-labs** [comment]
> Any link or help on how to train a model using your combined dataset 3?

Hi, please refer to our another work on https://doi.org/10.1007/978-3-031-37586-6_20 or https://github.com/softwaresec-labs/ACVED

**Comment by Drjacky** [comment]
@softwaresec-labs https://github.com/softwaresec-labs/ACVED/issues/1
